# Generated by Django 2.1.4 on 2018-12-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('author', models.CharField(max_length=256, verbose_name='作者')),
                ('localurl', models.CharField(max_length=256, verbose_name='链接')),
                ('imgurl', models.CharField(max_length=256, verbose_name='图片链接')),
                ('time', models.CharField(max_length=256, verbose_name='时间')),
                ('review', models.CharField(max_length=256, verbose_name='浏览')),
                ('memage', models.CharField(max_length=256, verbose_name='留言量')),
                ('code', models.CharField(max_length=256, verbose_name='摘要')),
                ('local', models.CharField(max_length=256, verbose_name='标签')),
                ('data', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='评论文章')),
                ('imgurl', models.CharField(max_length=256, verbose_name='头像链接')),
                ('time', models.CharField(max_length=256, verbose_name='评论时间')),
                ('name', models.CharField(max_length=256, verbose_name='评论者')),
                ('content', models.CharField(max_length=256, verbose_name='留言内容')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='昵称')),
                ('imgurl', models.CharField(max_length=256, verbose_name='头像链接')),
                ('url', models.CharField(max_length=256, verbose_name='友情链接')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=256, verbose_name='时间')),
                ('title', models.CharField(max_length=256, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='音乐名')),
                ('artlist', models.CharField(max_length=256, verbose_name='演唱者')),
                ('lrc', models.CharField(max_length=256, verbose_name='歌词')),
                ('theme', models.CharField(max_length=256, verbose_name='主题')),
                ('url', models.CharField(max_length=256, verbose_name='音乐源')),
                ('cover', models.CharField(max_length=256, verbose_name='图片')),
            ],
        ),
    ]
